export const size = {
  xxhuge:60,
  huge: 50,
  xxxtitle: 38,
  xxtitle: 36,
  xtitle: 34,
  title: 32,
  h1: 30,
  h2: 28,
  h3: 26,
  h4: 25,
  h5: 24,
  h6: 22,
  xxlarge: 20,
  xlarge: 19,
  large: 18,
  medium: 17,
  normal: 16,
  small: 15,
  xsmall: 14,
  xxsmall: 13,
  tiny: 12,
  xtiny: 11,
  xxtiny: 10,
  xxxtiny: 9,
};

export const family = {
  RedHatDisplay_Black: 'RedHatDisplay-Black',
  RedHatDisplay_BlackItalic: 'RedHatDisplay-BlackItalic',
  RedHatDisplay_Bold: 'RedHatDisplay-Bold',
  RedHatDisplay_BoldItalic: 'RedHatDisplay-BoldItalic',
  RedHatDisplay_ExtraBold: 'RedHatDisplay-ExtraBold',
  RedHatDisplay_ExtraBoldItalic: 'RedHatDisplay-ExtraBoldItalic',
  RedHatDisplay_Italic: 'RedHatDisplay-Italic',
  RedHatDisplay_Light: 'RedHatDisplay-Light',
  RedHatDisplay_LightItalic: 'RedHatDisplay-LightItalic',
  RedHatDisplay_Medium: 'RedHatDisplay-Medium',
  RedHatDisplay_MediumItalic: 'RedHatDisplay-MediumItalic',
  RedHatDisplay_Regular: 'RedHatDisplay-Regular',
  RedHatDisplay_SemiBold: 'RedHatDisplay-SemiBold',
  RedHatDisplay_SemiBoldItalic: 'RedHatDisplay-SemiBoldItalic',
  // Poppins_BoldItalic: 'Poppins-BoldItalic',
  // Poppins_Bold: 'Poppins-Bold',
  // Poppins_BlackItalic: 'Poppins-BlackItalic',
  // Poppins_Black: 'Poppins-Black',
  // Giddyup_Std: 'Giddyup-Std',
};
